Problem: missing Ledger support (fix #14)
crypto-com/chain-desktop-wallet pull request #209
Opened 2021-01-25 13:54 UTC by leejw51crypto

Solution: add ledger support (Fix #14)

to use ledger, 
1. create 
in creating wallet, if type is ledger, call this
createLedgerDevice  : singleton, each instance doesn't matter, automatically connect, disconnect for each call
and store address in Wallet which is stored in nedb-promises.

for signing, if wallet is ledger type, call ledger signing, it detects pubkey automatically and ask user automatically.

2. you can
 getPubKey(index: number): Promise<Bytes>;
  getAddress(index: number): Promise<string>;
  sign(message: Bytes): Promise<Bytes>; <- search by pubkey , automatically
  
3. to choose between webuse or native
 // true: webusb,  false:native
export const useWebusbForLedger = true;

4. examples are like below
```
to get address)
const device: ISignerProvider = createLedgerDevice();
const address = await device.getAddress(0);

to get signer)
const signerProvider: ISignerProvider = createLedgerDevice();
const tmpWalletConfig = DefaultWalletConfigs.MyNetConfig;
const ledgerTransactionSigner = new LedgerTransactionSigner(
  tmpWalletConfig,
  signerProvider,
);
```

2021-01-26 04:10 UTC, linfeng-crypto submitted a review, later dismissed

2021-02-03 09:40 UTC, leejw51crypto commented
rebased

2021-02-03 11:45 UTC, leejw51crypto commented
first wallet issue fixed
and rebased

2021-02-03 12:00 UTC, leejw51crypto commented on src/service/WalletService.ts
> +    if (transferRequest.walletType === 'ledger') {
ok, i'll modify

2021-02-03 15:37 UTC, leejw51crypto commented
rebasing now

2021-02-03 15:45 UTC, leejw51crypto commented
done

2021-02-04 07:14 UTC, leejw51crypto commented
working on addressPrefix , make it use current wallet.config.network.addressPrefix

2021-02-04 08:36 UTC, leejw51crypto commented
rebased

2021-02-05 15:09 UTC, leejw51crypto commented
audit can be resolved, when cosmosjs is updated

2021-02-08 02:14 UTC, leejw51crypto commented
rebased

2021-02-08 08:40 UTC, CeruleanAtMonaco commented on package.json
> +    "electron": "^11.1.1",
should fix dependency versions

2021-02-08 08:57 UTC, leejw51crypto commented on package.json
> +    "electron": "^11.1.1",
ok, will fix the version

2021-02-08 12:34 UTC, leejw51crypto commented
removed cosmosjs dependency,
rebased

2021-02-08 19:37 UTC, eddycpc requested changes

2021-02-08 19:37 UTC, eddycpc commented on .github/workflows/build.yml
>      steps:
This step might have an issue since this build file is not running. Can you fix the reported error?

> every step must define a `uses` or `run` key

2021-02-09 02:13 UTC, leejw51crypto commented on .github/workflows/build.yml
>      steps:
i'll check

2021-02-09 08:40 UTC, leejw51crypto commented
rebased

2021-02-09 08:52 UTC, leejw51crypto commented
fixed lgtm issue

2021-02-09 12:06 UTC, leejw51crypto commented
upgrade to chain-jslib 0.0.8

2021-02-09 16:04 UTC, leejw51crypto commented
removed fix.sh

2021-02-10 07:08 UTC, eddycpc requested changes

2021-02-10 07:08 UTC, eddycpc commented on src/service/signers/LedgerTransactionSigner.ts
> +    transaction.fee = '5000';
```suggestion
    transaction.fee = `${FIXED_DEFAULT_FEE}`;
```

2021-02-10 10:50 UTC, leejw51crypto commented
removed fix.sh

2021-02-10 11:34 UTC, leejw51crypto commented on src/service/signers/LedgerTransactionSigner.ts
> +    transaction.fee = '5000';
thanks

2021-02-10 19:20 UTC, eddycpc commented on src/pages/create/create.tsx
> +        nodeUrl: 'http://mynode',
This input default node for the custom config  is invalid by default, can we replace it with localhost/127.0.0.1 ?

2021-02-11 08:25 UTC, eddycpc approved these changes

2021-02-11 12:30 UTC, leejw51crypto commented on src/pages/create/create.tsx
> +        nodeUrl: 'http://mynode',
ok, i'll modifiy

2021-02-12 07:10 UTC, eddycpc approved these changes

2021-02-12 07:11 UTC, merged