Problem: missing button of  in confirming tx (fix #262)
crypto-com/chain-desktop-wallet pull request #263
Opened 2021-02-20 06:53 UTC by leejw51crypto

Solution: add `check ledger` button in confirm tx page

2021-02-20 10:30 UTC, leejw51crypto commented
check ledger button will move to `receive` page

2021-02-22 07:24 UTC, eddycpc commented
Can you please share a screenshot since this is a UI/UX PR?

That would give reviewers a quick idea of the change. You might realize most of our UI/UX PRs have screenshots in them.

2021-02-22 07:27 UTC, eddycpc requested changes

2021-02-22 07:27 UTC, eddycpc commented on src/pages/send/send.tsx
> +      </Form.Item>
Why is this a form input item?

This value is not expected to be modified. If a user changes the `senderAddress`  in this input, it won't change anything because it's already implied that `senderAddress` is the address of the current `session.wallet`

2021-02-22 08:11 UTC, eddycpc commented
You can fix the audit issue with this https://github.com/crypto-com/chain-desktop-wallet/pull/259/commits/46c07e6600e37e4bf3294b36fef540f4520ec35d

2021-02-22 08:20 UTC, leejw51crypto commented on src/pages/send/send.tsx
> +      </Form.Item>
agreed, i'll change it

2021-02-22 08:20 UTC, leejw51crypto commented
i'll post screenshot

2021-02-22 11:03 UTC, leejw51crypto commented
sender page
sender address added

![Uploading image.png…]()

2021-02-22 11:05 UTC, leejw51crypto commented
receive page

![image](https://user-images.githubusercontent.com/51560997/108699974-512e8e00-7549-11eb-9636-05f5b771e9c4.png)

2021-02-22 11:10 UTC, leejw51crypto commented
send page
![image](https://user-images.githubusercontent.com/51560997/108700486-05301900-754a-11eb-8039-bb6ebdc9ed0a.png)

2021-02-22 11:12 UTC, leejw51crypto commented
receive page
![image](https://user-images.githubusercontent.com/51560997/108700665-47f1f100-754a-11eb-897f-398d72d71f1b.png)

2021-02-22 13:08 UTC, eddycpc commented
> send page
> ![image](https://user-images.githubusercontent.com/51560997/108700486-05301900-754a-11eb-8039-bb6ebdc9ed0a.png)

The sender address should probably be shown on confirm popup, let's remove it from this form. In sort of looks out of place.

2021-02-22 13:58 UTC, crypto-matto commented
So the suggested modifications are:
1. In `Receive Page`, having a `Check Ledger` button positioned inside the card layout
2. In `Send Page`, showing `sender` address inside the confirmation popup

2021-02-22 16:55 UTC, crypto-matto commented
<img width="588" alt="螢幕截圖 2021-02-23 上午12 38 24" src="https://user-images.githubusercontent.com/74586409/108741509-c7df8180-7571-11eb-88bf-f3b3cc91c2ba.png">
<img width="618" alt="螢幕截圖 2021-02-23 上午12 38 37" src="https://user-images.githubusercontent.com/74586409/108741528-cada7200-7571-11eb-9ef0-08e83c991cc3.png">
<img width="601" alt="螢幕截圖 2021-02-23 上午12 41 24" src="https://user-images.githubusercontent.com/74586409/108741541-cc0b9f00-7571-11eb-8b7f-0c6000432db0.png">

2021-02-22 16:59 UTC, crypto-matto commented
<img width="598" alt="螢幕截圖 2021-02-23 上午12 57 46" src="https://user-images.githubusercontent.com/74586409/108742122-5bb14d80-7572-11eb-847b-3fee25a80aef.png">

2021-02-22 17:00 UTC, crypto-matto submitted a review, later dismissed

2021-02-23 05:02 UTC, leejw51crypto commented
thanks, that's better.

2021-02-23 06:36 UTC, eddycpc requested changes

2021-02-23 06:36 UTC, eddycpc commented on src/pages/receive/receive.tsx
> +      alert(`Cannot detect ledger device ${e}`);
Please let's remove this alert here.

2021-02-23 08:55 UTC, crypto-matto commented on src/pages/receive/receive.tsx
> +      alert(`Cannot detect ledger device ${e}`);
<img width="1190" alt="螢幕截圖 2021-02-23 下午4 55 06" src="https://user-images.githubusercontent.com/74586409/108820981-f011c380-75f7-11eb-81d2-66cea80fa89b.png">
Used this notification popup instead.

2021-02-23 08:56 UTC, crypto-matto approved these changes

2021-02-23 09:10 UTC, eddycpc approved these changes

2021-02-23 09:13 UTC, merged