Problem: adding console.log for tx failure error (fix #345)
crypto-com/chain-desktop-wallet pull request #346
Opened 2021-03-27 09:53 UTC by leejw51crypto

Solution:add debug log

2021-03-27 15:58 UTC, eddycpc commented on src/service/rpc/NodeRpcService.ts
> +      console.log(`tx failure= ${JSON.stringify(broadcastResponse)}`);
I'm wondering if there's a reason would we want to console log in release builds? 

The console tab is being hidden in release builds, so even if it logs we can't see the logs

2021-03-27 15:58 UTC, eddycpc requested changes
Left a comment

2021-03-28 02:15 UTC, leejw51crypto commented on src/service/rpc/NodeRpcService.ts
> +      console.log(`tx failure= ${JSON.stringify(broadcastResponse)}`);
ok, i see

2021-03-28 02:15 UTC, leejw51crypto commented
replace this issue with this one
https://github.com/crypto-com/chain-desktop-wallet/issues/349

2021-03-28 02:15 UTC, closed without merging