Problem: extend ledger wallet address limit to maximum (fix #422)
crypto-com/chain-desktop-wallet pull request #425
Opened 2021-04-09 11:47 UTC by leejw51crypto

Solution: extend ledger maximum address index to
99999,9999   <- 9 digits

2021-04-09 11:54 UTC, calvinaco commented on src/config/StaticConfig.ts
> +export const LedgerWalletMaximum = 999999999;
Why don't put `2147483647` but `999999999` here?

2021-04-09 13:14 UTC, leejw51crypto commented on src/config/StaticConfig.ts
> +export const LedgerWalletMaximum = 999999999;
i'll change to 2147483647, ax maximum (inclusive)

2021-04-09 17:15 UTC, ytbigvinny27 approved these changes

2021-04-10 01:02 UTC, leejw51crypto commented
chain-maind keys add ok --index=2147483647

from 2147483648, it's error
```
 chain-maind keys add ok --index=2147483648
override the existing name ok [y/N]: y
Error: invalid BIP 32 path m/44'/394'/0'/0/2147483648: strconv.ParseUint: parsing "2147483648": value out of range
Usage:
```

2021-04-10 03:56 UTC, crypto-matto commented
Expert Mode checking & error message is added in Sending. 
`Delegate`, `Redelegate`, `Undelegate`, `Withdraw Reward` to be added.

2021-04-12 07:02 UTC, eddycpc commented
@leejw51crypto @crypto-matto is this PR ready for merging now?

Also, there are some merge conflicts.

2021-04-12 07:49 UTC, crypto-matto commented
> @leejw51crypto @crypto-matto is this PR ready for merging now?
> 
> Also, there are some merge conflicts.

Not yet for my side. I'll update you when it's ready.

2021-04-12 09:42 UTC, leejw51crypto commented
checking rebased code now

2021-04-12 11:22 UTC, eddycpc requested changes

2021-04-12 11:22 UTC, eddycpc commented on src/pages/send/send.tsx
> +        }
Can we extract this repeated logic into a function that returns a boolean to set up the `setLedgerIsExpertMode` state ?

2021-04-12 11:52 UTC, leejw51crypto commented on src/pages/send/send.tsx
> +        }
ok, i'll change it

2021-04-13 06:36 UTC, eddycpc submitted a review, later dismissed
LGTM

2021-04-13 10:13 UTC, crypto-matto commented
There are some logics to be fixed. 
There are 3 scenarios:
1. Ledger `connection successful` with `Expert Mode`
2. Ledger `connection successful` with `Normal Mode`
3. Ledger `connection NOT successful`
```
export async function detectLedgerExpertMode(): Promise<boolean> {
  try {
    const device = createLedgerDevice();
    await device.getPubKey(LedgerWalletMaximum, false);
    return true;
  } catch (err) {
    return false;
  }
}
```
For this function checking, it can only differentiate scenario 1 (by returning `true`) from 2 & 3, but cannot differentiate between scenario 2 and 3. Both scenario 2 & 3 will return false. 

My original checking for `isLedgerExpertMode` will return `true` & the error message shows `Please ensure that your have enabled Expert mode on your ledger device.` for scenario 2 only. 

Right now, the error message will show up for scenario 1:
```
      {ledgerIsExpertMode ? (
        <div>Please ensure that your have enabled Expert mode on your ledger device.</div>
      ) : (
        ''
      )}
```

2021-04-13 12:32 UTC, leejw51crypto commented
ok, i'll add two error states
1. not connected <- error state
2. need expert mode to generate over 100 address index  <- error state
3. else <- normal , not showing error messag

2021-04-14 01:26 UTC, leejw51crypto commented
<img width="362" alt="image" src="https://user-images.githubusercontent.com/51560997/114640821-777bd900-9d03-11eb-8122-cd5564d1f8fb.png">

2021-04-14 01:26 UTC, leejw51crypto commented
message displayed correctly

2021-04-14 04:24 UTC, calvinaco commented on src/service/LedgerService.ts
> +  }
How do you distinguish it is Ledger disconnected or just advance mode is not enabled here?

2021-04-14 04:51 UTC, leejw51crypto commented on src/service/LedgerService.ts
> +  }
when flow  reached here, we don't know whether ledger disconnected or not expert mode.
by calling this api one more time, we can know whether it's by expert mode issue or not.

2021-04-14 04:52 UTC, leejw51crypto commented on src/service/LedgerService.ts
> +  }
to be more clear, i'll add another feedback value to give information.

2021-04-14 06:34 UTC, crypto-matto commented
Able to detect scenarios 1,2,3 now 👍🏻 

<img width="548" alt="螢幕截圖 2021-04-14 下午2 29 43" src="https://user-images.githubusercontent.com/74586409/114664455-4bc21880-9d2e-11eb-96f3-8e7c1ea6d02e.png">

One more minor thing, is it able to remove duplicated `[Conditions not satisfied]` text error ? 

<img width="551" alt="螢幕截圖 2021-04-14 下午2 29 17" src="https://user-images.githubusercontent.com/74586409/114664444-48c72800-9d2e-11eb-98fa-1f91ca54c032.png">

2021-04-14 06:34 UTC, crypto-matto approved these changes

2021-04-14 06:45 UTC, eddycpc approved these changes

2021-04-14 06:46 UTC, calvinaco submitted a review, later dismissed

2021-04-14 06:52 UTC, leejw51crypto commented
yes,it's can be removed 
because it's not used in other places

2021-04-14 07:35 UTC, merged