Problem (Fix #446): No default sorting on wallet page
crypto-com/chain-desktop-wallet pull request #447
Opened 2021-04-16 09:44 UTC by crypto-matto

2021-04-16 15:40 UTC, eddycpc commented
I remember there used to be a sorting based on current selected wallet, do we still have the current selected wallet on top ?

2021-04-19 08:57 UTC, crypto-matto commented
> I remember there used to be a sorting based on current selected wallet, do we still have the current selected wallet on top ?

Since the sorting is on the frontend side, I think that would require a dedicated fixed area, outside of the table, in order to do so.

2021-04-19 10:13 UTC, crypto-matto commented
Fixed row for current selected wallet & extracted from wallet list. 
<img width="1276" alt="螢幕截圖 2021-04-19 下午5 52 31" src="https://user-images.githubusercontent.com/74586409/115220215-dba30080-a13a-11eb-9e87-7d420ef27bee.png">

2021-04-19 11:20 UTC, crypto-matto commented
Fixed row for current selected wallet & extracted from wallet list.

<img width="1341" alt="螢幕截圖 2021-04-19 下午7 19 36" src="https://user-images.githubusercontent.com/74586409/115228386-4573d800-a144-11eb-9bc6-ee7309f91455.png">

2021-04-19 11:38 UTC, ytbigvinny288 approved these changes

2021-04-19 19:39 UTC, ytbigvinny288 approved these changes

2021-04-19 20:28 UTC, ytbigvinny288 approved these changes

2021-04-21 19:18 UTC, ytbigvinny288 approved these changes

2021-04-27 08:52 UTC, eddycpc commented
The icon on the Ledger wallet type looks asymmetric comparing to the normal wallet.

- I think if we add icon for one wallet type we should also add the icon to the other type

2021-04-27 08:54 UTC, eddycpc requested changes

2021-04-27 08:54 UTC, eddycpc commented on src/pages/wallet/wallet.tsx
> +                {walletType === LEDGER_WALLET_TYPE ? <Icon component={IconLedger} /> : ''}
If we add an icon for Ledger let's also add an icon for the normal wallet type, that way we keep things symmetrical

2021-04-27 10:13 UTC, crypto-matto commented
<img width="1024" alt="螢幕截圖 2021-04-27 下午6 12 48" src="https://user-images.githubusercontent.com/74586409/116225247-30bac400-a784-11eb-881a-b1db71328232.png">

2021-04-27 10:17 UTC, eddycpc approved these changes

2021-04-27 10:18 UTC, merged