Nfts Frontend : Add NFT UI support
crypto-com/chain-desktop-wallet pull request #501
Opened 2021-06-01 08:59 UTC by crypto-matto

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/chain-desktip-wallet/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`yarn build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`yarn test`)
- [ ] Have you checked your code formatting is correct? (`yarn lint:js`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`yarn audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/chain-desktop-wallet/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/chain-desktop-wallet/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

Preview:
<img width="1275" alt="螢幕截圖 2021-06-01 下午4 54 03" src="https://user-images.githubusercontent.com/74586409/120296159-6a8a6780-c2fa-11eb-90ed-74006ec765f5.png">
<img width="1276" alt="螢幕截圖 2021-06-01 下午4 54 13" src="https://user-images.githubusercontent.com/74586409/120296177-6e1dee80-c2fa-11eb-88d1-288e027540ca.png">
<img width="1275" alt="螢幕截圖 2021-06-01 下午4 54 22" src="https://user-images.githubusercontent.com/74586409/120296179-6f4f1b80-c2fa-11eb-949a-b82780c90b47.png">
<img width="1267" alt="螢幕截圖 2021-06-01 下午4 58 32" src="https://user-images.githubusercontent.com/74586409/120296358-9e658d00-c2fa-11eb-81a5-a08f2f73f0d7.png">

2021-06-02 19:27 UTC, eddycpc commented on src/service/rpc/ChainIndexingAPI.ts
> +
Is there a way to do this request in a bulk instead of going one by one, doing this way is likely going to slow down quite a lot as the NFT count grows?

We can request the marketplace team to provide this API

2021-06-04 10:55 UTC, eddycpc commented on src/service/WalletService.ts
> +      console.log('saved nfts');
You can clean up these logs now

2021-06-04 10:58 UTC, eddycpc commented on src/service/rpc/ChainIndexingAPI.ts
> +      const nftMarketplaceData = await croNftApi.getNftListMarketplaceData(payload);
I think the request should be partitioned into smaller batches and then append on every iteration

2021-06-04 10:59 UTC, eddycpc commented on src/service/rpc/ChainIndexingAPI.ts
> +    let nftListWithMarketplaceData;
I would avoid mutating this property, I would suggest a return in the try block and another return in the catch block, which would remove the need to mutate these lists variables.

2021-06-04 11:01 UTC, eddycpc requested changes

2021-06-04 11:01 UTC, eddycpc commented on src/service/rpc/ChainIndexingAPI.ts
> +      });
Can we just return directly in the catch block and preferably avoid mutating the variable declared to the top.

```
return  nftLists.map((item, idx) => {
        return {
          ...nftLists[idx],
          isMintedByCDC: false,
          marketplaceLink: '',
        };
      });


```

2021-06-04 11:02 UTC, eddycpc commented on src/service/rpc/ChainIndexingAPI.ts
> +    return nftListWithMarketplaceData;
```suggestion
```

2021-06-04 11:13 UTC, crypto-matto commented on src/service/rpc/ChainIndexingAPI.ts
> +      const nftMarketplaceData = await croNftApi.getNftListMarketplaceData(payload);
New Venture team says they'll limit to 10 items. I'll break them down into pieces of 10.

2021-06-06 05:29 UTC, eddycpc approved these changes

2021-06-06 14:36 UTC, merged