Transfer NFT UI Flow with optimized layout
crypto-com/chain-desktop-wallet pull request #517
Opened 2021-06-09 04:37 UTC by crypto-matto

Flow: 
1. Transfer NFT Form
2. Ask for App Password
3. Confirm Transfer NFT Detail
4. Success / Error Popup
<img width="1257" alt="螢幕截圖 2021-06-09 下午12 33 42" src="https://user-images.githubusercontent.com/74586409/121294014-41cc2880-c91f-11eb-968f-465d15a1b36f.png">
<img width="1267" alt="螢幕截圖 2021-06-09 下午12 34 03" src="https://user-images.githubusercontent.com/74586409/121294024-45f84600-c91f-11eb-8ea3-957eb2787a5c.png">
<img width="1268" alt="螢幕截圖 2021-06-09 下午12 34 18" src="https://user-images.githubusercontent.com/74586409/121294029-47297300-c91f-11eb-93d8-5924bd698e88.png">
<img width="1267" alt="螢幕截圖 2021-06-09 下午12 35 20" src="https://user-images.githubusercontent.com/74586409/121294032-47c20980-c91f-11eb-9819-bbe6d729282c.png">

2021-06-09 18:47 UTC, crypto-matto commented
Added NFT Transaction on Home Page
<img width="1023" alt="螢幕截圖 2021-06-10 上午2 36 03" src="https://user-images.githubusercontent.com/74586409/121411180-f1dc7880-c995-11eb-9545-0eb006b15076.png">

2021-06-09 20:28 UTC, eddycpc requested changes

2021-06-09 20:28 UTC, eddycpc commented on src/pages/home/home.tsx
> +    if (transfer.messageType === 'MsgIssueDenom') {
Should we use an enum or constants for this, instead of checking with in-place string 'MsgIssueDenom'

2021-06-09 20:50 UTC, eddycpc requested changes

2021-06-09 20:50 UTC, eddycpc commented on src/pages/nft/nft.tsx
> +
I think after a successful NFT transfer, we can call `walletService.retrieveNFTs()` to update the account NFT  recoil state.

> This way if an NFT was sent to another address, it won't keep being shown again in the wallet since we have loaded immediately the latest state.

2021-06-10 07:35 UTC, eddycpc commented
<img width="330" alt="Screen Shot 2021-06-10 at 10 29 47 AM" src="https://user-images.githubusercontent.com/73159521/121483391-d0e84780-c9d6-11eb-8fc0-3b40b6202aad.png">

We can use this column to customize a little bit the text we show, 
if the tx is of type transfer we can do a few manipulations like 👇

-  If the current wallet address is the one receiving, let's just say here **"Receive NFT"**
-  If the current wallet address is the one sending,  **"Sent NFT"**

If the transaction failed we can just say "Failed Transfer", or "Failed Mint", etc, ...

This way we would be using this one column for many purposes and thus we save space, we also provide much more clarity to the user. We can rename the column from "Type" to "Status", generally most users care about copy text they can understand.

Let me know what you think about this @crypto-matto 🙏

2021-06-10 08:13 UTC, crypto-matto commented
Avoid overlapping modals
<img width="1268" alt="螢幕截圖 2021-06-10 下午4 13 15" src="https://user-images.githubusercontent.com/74586409/121489571-ca71c400-ca06-11eb-972e-d640500131dd.png">
<img width="1266" alt="螢幕截圖 2021-06-10 下午4 13 06" src="https://user-images.githubusercontent.com/74586409/121489589-ce054b00-ca06-11eb-8d9e-0e696f6f4538.png">
<img width="1253" alt="螢幕截圖 2021-06-10 下午4 12 59" src="https://user-images.githubusercontent.com/74586409/121489592-cf367800-ca06-11eb-892d-7bd66cb658eb.png">

Optimize NFT Transaction Types
<img width="1025" alt="螢幕截圖 2021-06-10 下午4 10 26" src="https://user-images.githubusercontent.com/74586409/121489181-6949f080-ca06-11eb-9a16-fee5fa0ab7e1.png">

2021-06-10 08:51 UTC, merged