Feature - Add NFT mint section
crypto-com/chain-desktop-wallet pull request #531
Opened 2021-06-27 19:09 UTC by crypto-matto

<img width="1322" alt="螢幕截圖 2021-06-28 上午3 05 28" src="https://user-images.githubusercontent.com/74586409/123556504-2a65ba00-d7be-11eb-96e0-df082429b213.png">
<img width="1324" alt="螢幕截圖 2021-06-28 上午3 04 53" src="https://user-images.githubusercontent.com/74586409/123556507-2afe5080-d7be-11eb-8498-a3894db32790.png">
<img width="1319" alt="螢幕截圖 2021-06-28 上午3 05 38" src="https://user-images.githubusercontent.com/74586409/123556502-29348d00-d7be-11eb-989c-0a6ae5988d79.png">
<img width="1322" alt="螢幕截圖 2021-06-28 上午3 07 23" src="https://user-images.githubusercontent.com/74586409/123556499-28036000-d7be-11eb-8923-94c3b17e90d5.png">
<img width="542" alt="螢幕截圖 2021-06-28 上午3 07 52" src="https://user-images.githubusercontent.com/74586409/123556496-25086f80-d7be-11eb-8829-32755fc09b4f.png">

2021-06-28 07:28 UTC, eddycpc commented on src/pages/nft/nft.tsx
> +
I wonder why this part is commented out, it can be used to sync the latest created NFTs into the local recoil store

2021-06-28 07:29 UTC, eddycpc commented on src/pages/nft/nft.tsx
> +
We can remove unused code

2021-06-28 13:39 UTC, eddycpc requested changes

2021-06-28 13:39 UTC, eddycpc commented on src/pages/home/home.tsx
> +                            ? item?.tokenData.name
I would suggest we try to use the `drop` value if it's available after realizing the name property does not exist.

So basically I would do something like :
1.  If item `tokenData.name` exists then display it` tokenData.name`
2. If `tokenData.name` does not exist try to show `tokenData.drop`
3. Finally if `tokenData.drop` does not exist then use `${item?.denomId} - #${item?.tokenId}`

2021-06-29 06:48 UTC, eddycpc requested changes

2021-06-29 06:48 UTC, eddycpc commented on src/service/WalletService.ts
> +      const nftDenomData = await chainIndexAPI.fetchNftDenomData(denomId);
I'm curious what do we pass exactly here is it `denomId` or `denom name` ?

That's because in the UI form for mint NFT, the input field is being called **denom name**

2021-06-29 08:42 UTC, eddycpc commented on src/pages/nft/nft.tsx
> +          <TabPane tab="NFT Mint" key="2">
```suggestion
          <TabPane tab="Mint NFT" key="2">
```

2021-06-29 08:58 UTC, crypto-matto commented on src/service/WalletService.ts
> +      const nftDenomData = await chainIndexAPI.fetchNftDenomData(denomId);
If you look at one of our [official minted NFT](https://crypto.org/explorer/nfts/tokens/k9528183ec3b706ca28d3f6fc5d31cf60/edition63289) , both `denomId` and `denomName` are identical, but Denom Name would be a more user-friendly. 

https://crypto.org/explorer/api/v1/nfts/denoms/k9528183ec3b706ca28d3f6fc5d31cf60

2021-06-29 09:02 UTC, eddycpc requested changes

2021-06-29 09:02 UTC, eddycpc commented on src/pages/home/home.tsx
> +  const renderNftTitle = (_nft: NftProcessedModel | undefined, length: number = 0) => {
I think the `length` check in many places is not necessary.

The `ellipsis` function is already doing that in the implementation. Let's remove it and keep the code much cleaner.

You can see in the definition below that the code is doing exactly what you're replicating here.
```
export function ellipsis(str: string, len: number) {
  return str.length <= len ? `${str}` : `${str.substr(0, len)}...`;
}
```

2021-06-29 10:31 UTC, eddycpc approved these changes

2021-06-29 10:43 UTC, crypto-matto commented
- Card grid image in square-cover
<img width="1018" alt="螢幕截圖 2021-06-29 下午5 49 22" src="https://user-images.githubusercontent.com/74586409/123778271-838b3600-d903-11eb-81eb-52be6d0bdac2.png">

- Loading spin when image loading
<img width="508" alt="螢幕截圖 2021-06-29 下午6 28 42" src="https://user-images.githubusercontent.com/74586409/123782432-ed0d4380-d907-11eb-851a-8cf16ae4809e.png">

2021-06-29 11:14 UTC, merged