Problem: Add EVM and CronosClient
crypto-com/chain-desktop-wallet pull request #620
Opened 2021-08-04 17:44 UTC by cdc-Hitesh

2021-08-04 19:56 UTC, crypto-3dd commented on src/service/rpc/clients/EVMClient.ts
> +    }
I don't think this is really needed, especially on the desktop wallet, let me know if there's a use case for this one currently

2021-08-04 19:58 UTC, crypto-3dd reviewed
This is looking pretty good already, good start!

2021-08-04 20:05 UTC, crypto-3dd commented on src/service/cronos/CronosClient.ts
> +
Overall, all looks good, I would suggest now also to add some mock tests, these tests help document how to use the API.

Have a look at how we are doing in the `NodeRpcService.spec` test class

2021-08-05 05:22 UTC, cdc-Hitesh commented on src/service/rpc/clients/EVMClient.ts
> +    }
I have observed whenever we are working with:
- transaction receipt fetching 
- Showing users the status of our connected nodes

checking the node syncing status helps.

Still, let me know if you want it to be removed.

2021-08-05 05:23 UTC, cdc-Hitesh commented on src/service/cronos/CronosClient.ts
> +
Noted.
I will add.

2021-08-05 15:29 UTC, crypto-3dd requested changes

2021-08-05 15:29 UTC, crypto-3dd commented on src/service/cronos/CronosClient.ts
> +        throw new Error("Method not implemented.");
You haven't found yet a service to pull transactions history data?

You might ask Calvin or any other core dev working on `Cronos`, they might help on this

2021-08-05 15:38 UTC, cdc-Hitesh commented on src/service/cronos/CronosClient.ts
> +        throw new Error("Method not implemented.");
Hey @crypto-3dd 
I didn't push it sorry. It was done locally.
Thanks

2021-08-06 06:42 UTC, crypto-3dd requested changes

2021-08-06 06:42 UTC, crypto-3dd commented on src/service/cronos/CronosClient.ts
> +const cronosExplorerAPIBaseURI = 'https://cronos-explorer.crypto.org/api';
Instead of having this value hardcoded, I would suggest having it as a constructor property, that would add more flexibility for the `CronosClient` class. And the explorer URL can be UI configurable object.

2021-08-06 07:28 UTC, crypto-3dd commented on src/service/rpc/clients/EVMClient.ts
> +    }
I wonder if this `setter` is needed if the web3 param can be set immediately from the constructor?

I would probably make the web3 immutable and just keep the constructor, the getter and setter would not be needed doing that way.

2021-08-06 07:43 UTC, cdc-Hitesh commented on src/service/cronos/CronosClient.ts
> +const cronosExplorerAPIBaseURI = 'https://cronos-explorer.crypto.org/api';
Okay sure it makes sense.
Also, I think this value might come from any `StaticConfig` variable.

2021-08-06 07:45 UTC, cdc-Hitesh commented on src/service/rpc/clients/EVMClient.ts
> +    }
I have just kept the `setter` for future-ready scenario. Let's say if the web3 instance is to be changed on the fly or creating a fallback mechanism.

But again, there is no concrete future use case I see.

Do you want me to remove it or keep it for now?

2021-08-06 15:52 UTC, crypto-matto commented
The `yarn audit` error shall be fixed by adding an updated enough package version, as suggested in the error, under `package.json` => `resolutions`
```
  "resolutions": {
    ...,
    "tar": "6.1.1"
  }
```

2021-08-06 23:11 UTC, cdc-Hitesh commented
> The `yarn audit` error shall be fixed by adding an updated enough package version, as suggested in the error, under `package.json` => `resolutions`
> 
> ```
>   "resolutions": {
>     ...,
>     "tar": "6.1.1"
>   }
> ```

Thanks Matthew.

2021-08-09 06:35 UTC, crypto-3dd approved these changes

2021-08-09 06:35 UTC, merged