Code clean up - Proper usage and handling of fees on EVM transactions
crypto-com/chain-desktop-wallet pull request #654
Opened 2021-08-30 14:50 UTC by crypto-3dd

- Proper handling of gasLimit and gasFee for cronos transactions
- Clean up code, use proper conversions utility methods

2021-08-30 18:46 UTC, mannutech requested changes

2021-08-30 18:46 UTC, mannutech commented on src/service/WalletService.ts
> +          transfer.gasLimit = Number(await cronosClient.estimateGas(txConfig));
This `Number` typecasting may not be safe here.

We can switch to `big.js`

2021-08-30 21:44 UTC, crypto-3dd commented on src/service/WalletService.ts
> +          transfer.gasLimit = Number(await cronosClient.estimateGas(txConfig));
> This Number typecasting may not be safe here.

Can you please elaborate on how unsafe it can be here?

Let me provide more details : 
- The gas estimate value here is guaranteed to forever fit in Number type and it doesn't have floating-point properties. it's a whole integer number.
- The price estimate is being returned in Gwei, which is guaranteed also to fit inside the Number type. The conversion to the small unit (Wei) is happening inside the `EvmTransactionSigner` class.

I might possibly miss something, let me know if there's something I'm missing on the unsafe part. Thanks.

2021-08-31 05:21 UTC, cdc-Hitesh commented on src/service/WalletService.ts
> +          transfer.gasLimit = Number(await cronosClient.estimateGas(txConfig));
Thanks for the explanation @crypto-3dd 

Generally, within blockchain value calculations for numbers, we use any big number handling library. Hence brought that general suggestion here.

Your explanation kind of clarifies the doubt.

2021-08-31 07:15 UTC, cdc-Hitesh commented on src/service/WalletService.ts
> +          transfer.gasLimit = Number(await cronosClient.estimateGas(txConfig));
I re-visited, looks good to me resolving.

2021-08-31 07:23 UTC, cdc-Hitesh approved these changes

2021-08-31 07:35 UTC, merged