[EVM] Cronos Frontend Step9
crypto-com/chain-desktop-wallet pull request #655
Opened 2021-08-31 03:17 UTC by crypto-matto

- [x] Add `Currency` settings
- [ ] Display market data with selected `Currency`
- [x] Merge `Send` & `Receive` Page into `Assets` Page
- [ ] Update with latest design from Design Team

2021-08-31 07:40 UTC, crypto-3dd requested changes

2021-08-31 07:40 UTC, crypto-3dd commented on src/config/StaticConfig.ts
> +  defaultCurrency: string;
Hey @crypto-matto I wonder if we really need this new property `defaultCurrency`  

- We already have `session.currency` which holds USD as the default currency, so we can just asssume whatever is stored inside `session.currency` is the current currency. 

- And when it's updated we would just update the session object and set the new currency.

- So we might not need an extra variable to track the fiat currency currently selected. That keeps much simpler since we are only tracking a single state variable.

2021-08-31 07:48 UTC, crypto-matto commented on src/config/StaticConfig.ts
> +  defaultCurrency: string;
Hi @crypto-3dd, sorry for causing the confusion. I forgot to delete this field here since I was using `defaultCurrency` in earlier commit, but I switched to use `session.currency` in commit https://github.com/crypto-com/chain-desktop-wallet/pull/655/commits/27bcd2a3f2f19b4cae77106f247aeae1039f9dbd .

2021-08-31 21:15 UTC, crypto-3dd requested changes

2021-08-31 21:15 UTC, crypto-3dd commented on src/pages/settings/settings.tsx
> +    );
This section might not scale well when new currencies are added.

You seem to hardcode currency data to only the primary asset, this section should work for all assets. 
If we want to hold market data in the setMarketData, it should be asset agnostic, it means when new assets are added it should normally work nevertheless.

2021-09-01 01:59 UTC, crypto-matto commented on src/pages/settings/settings.tsx
> +    );
Not sure if you want me to hardcode 'CRO' as the input parameter, or use either:
1. `walletService.retrieveDefaultWalletAsset()` (which is basically running the same for loop logic & pick the first asset)
2. `session.activeAsset`

I'm hardcoding to 'CRO' for the moment.

2021-09-01 06:35 UTC, crypto-3dd commented on src/pages/settings/settings.tsx
> +    );
What I meant is the market data is needed for all assets in the wallet, not only the primary asset.

If a user has 4 assets in the wallet they would want to have all assets with fiat currency conversion, not only the primary one.

2021-09-01 06:36 UTC, crypto-3dd requested changes

2021-09-01 06:36 UTC, crypto-3dd commented on src/config/StaticConfig.ts
> +export const DEFAULT_ASSET_SYMBOL = 'CRO';
Sorry, this is not very flexible. I don't understand yet why we would need to hardcode this.

2021-09-01 06:39 UTC, crypto-3dd commented on src/config/StaticConfig.ts
> +export const DEFAULT_CURRENCY_CODE = 'USD';
This is also not needed because the default fiat currency code is already held in the `session.currency` property

2021-09-01 06:43 UTC, crypto-3dd commented on src/pages/settings/settings.tsx
> +  const [defaultCurrencyState, setDefaultCurrencyState] = useState<string>(DEFAULT_CURRENCY_CODE);
```suggestion
  const [defaultCurrencyState, setDefaultCurrencyState] = useState<string>(currentSession.currency);
```

2021-09-01 06:46 UTC, crypto-3dd requested changes

2021-09-01 06:46 UTC, crypto-3dd commented on src/pages/settings/settings.tsx
> +      DEFAULT_ASSET_SYMBOL,
This can be problematic, it only fetches fiat currency data for **only one asset**.

If a wallet has more than 1 asset, **it's good to go ahead and fetch currency conversions for all the assets** in the wallet, not only one asset.

The proper approach here is to fetch `currencyMarketData` for all assets in the wallet

2021-09-01 07:02 UTC, crypto-3dd commented
<img width="357" alt="Screen Shot 2021-09-01 at 9 56 51 AM" src="https://user-images.githubusercontent.com/73159521/131626140-3c2598a5-950f-46aa-96ca-83d49769363c.png">

British Pound having a $ sign in front. I would we can make it flexible so that in the `SUPPORTED_CURRENCY`, we specify a symbol.

That way it can be picked up easily. Something close to the code below.

`SUPPORTED_CURRENCY[currentSession.currency].getSymbol()`

At the same time, `SUPPORTED_CURRENCY` can be given a type as an array or a map of Currencies i.e. `CurrencySupported`

```
export interface CurrencySupported {
    value: string;
    symbol: string;
    label: string;
}
```

2021-09-01 18:08 UTC, crypto-matto commented on src/pages/settings/settings.tsx
> +      DEFAULT_ASSET_SYMBOL,
Got your idea. I'll update in other places as well.

2021-09-02 05:50 UTC, crypto-3dd commented on src/storage/StorageService.ts
> +    return this.db.marketPriceStore.find<AssetMarketPrice>({ _id: new RegExp(currency) });
How does this `_id: new RegExp(currency)` work?

2021-09-02 05:52 UTC, crypto-3dd commented on src/config/StaticConfig.ts
> +  { value: 'USD', label: 'USD - $', symbol: '$' },
You can make this a typed array as suggested below, it would make it hard to mess up accidentally. And strong types are always preferred when possible.

2021-09-02 09:37 UTC, crypto-matto commented on src/storage/StorageService.ts
> +    return this.db.marketPriceStore.find<AssetMarketPrice>({ _id: new RegExp(currency) });
The `_id` are stored as:
- `CRO-USD`
- `CRO-GBP`
- `CRO-EUR`
- `CRONOS-USD`
- `ATOM-USD`
...
Therefore, buy using `new RegExp(currency)` it shall return all `_id`s containing the `currency` parameter.

2021-09-02 16:15 UTC, crypto-3dd commented on src/storage/StorageService.ts
> +    return this.db.marketPriceStore.find<AssetMarketPrice>({ _id: new RegExp(currency) });
That's very smart I didn't know NeDB allowed those types of queries.

2021-09-02 22:32 UTC, crypto-3dd approved these changes

2021-09-02 22:32 UTC, merged