Fix QA issues reported
crypto-com/chain-desktop-wallet pull request #679
Opened 2021-09-07 08:15 UTC by crypto-matto

- [x] Fix display of config settings not updated after `Save`
- [x] Fix incorrect explorer url for Address explorer page

2021-09-07 08:20 UTC, crypto-3dd requested changes

2021-09-07 08:20 UTC, crypto-3dd commented on src/pages/assets/assets.tsx
> +            explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'
Can you move the full URL to the configuration?

This is again not very flexible, because we are telling the front-end to know what **cronos** is. 

This reduces flexibility in case we need to add new assets, are we going to add other if/else here ? That wouldn't be very scalable.

It's preferable to update the config value so that it has **/address or /account in its url**. Front-end shouldn't do these things

2021-09-07 08:28 UTC, crypto-matto commented on src/pages/assets/assets.tsx
> +            explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'
Well said. I'll revise the Explorer URL mechanism.

2021-09-07 13:41 UTC, crypto-3dd commented on src/pages/assets/assets.tsx
> +            explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'
I suggested you add all the necessary bits inside the config explorer.

For instance instead of     explorerUrl: `'https://cronos-explorer.crypto.org',` we would just add the` /address` or `/account `bits.

That way the front-end will remain fairly simple.

2021-09-07 17:49 UTC, crypto-matto commented on src/pages/assets/assets.tsx
> +            explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'
I'm suggesting `explorerUrl` to change into an object:
```
explorerUrl: {
    home: 'https://crypto.org/explorer/',
    tx: 'https://crypto.org/explorer/tx',
    address: 'https://crypto.org/explorer/account',
    validator: 'https://crypto.org/explorer/validator',
}
```
Yet how to update all users’ existing config settings which were storing explorerUrl as string?

2021-09-07 18:39 UTC, crypto-3dd commented on src/pages/assets/assets.tsx
> +            explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'
I see, wonder if we need the `home` explorer section?

> Yet how to update all users’ existing config settings which were storing explorerUrl as string?

They will be recreating the assets via the popup we provide, which would bring newly updated config object

2021-09-08 11:01 UTC, crypto-3dd commented on src/config/StaticAssets.ts
> +  }
This switch might not be needed because `walletConfig` argument comes already with the `walletConfig.explorerUrl`

We can just pass it directly.

2021-09-08 11:02 UTC, crypto-3dd commented on src/pages/settings/settings.tsx
> +        // explorerUrl: settingsDataUpdate.indexingUrl!,
Is there a reason why we comment out this field?

2021-09-08 16:31 UTC, crypto-matto commented on src/pages/settings/settings.tsx
> +        // explorerUrl: settingsDataUpdate.indexingUrl!,
Indexing Url tends to be having `api` at the back, e.g. `https://crypto.org/explorer/croeseid4/api/v1/`, `https://cronos-explorer.crypto.org/api`, where `api/v1` and `api` exists.

2021-09-09 10:56 UTC, crypto-matto commented on src/pages/assets/assets.tsx
> +            explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'
I changed from `home` to `index` just to be clearer. The index page will be the same as the original `explorerUrl`

2021-09-09 10:57 UTC, crypto-matto commented on src/pages/settings/settings.tsx
> +        // explorerUrl: settingsDataUpdate.indexingUrl!,
Now I update `explorer` instead

2021-09-10 07:04 UTC, crypto-3dd commented on src/config/StaticAssets.ts
> +};
I think rendering-related functions shouldn't be in static assets file, this file doesn't know about rendering, it only holds assets configuration.

2021-09-10 07:05 UTC, crypto-3dd requested changes

2021-09-10 07:05 UTC, crypto-3dd commented on src/config/StaticAssets.ts
> +        url = `${explorerUrl}/${explorerUrl.indexOf('cronos') !== -1 ? 'address' : 'account'}`;
I think this hardcoding here of `cronos` might still be very problematic, what if we have new assets added ? are we expanding into another large if/else switch statement?

I would suggest just declare simple configurations and each asset will know how to handle their own configuration

2021-09-14 08:09 UTC, crypto-3dd commented on src/layouts/home/home.tsx
> +        allWallets.forEach(async wallet => {
I like this approach 👍  we would need to test it greatly to make sure it's doing what we expect it to do exactly

2021-09-14 08:11 UTC, crypto-3dd requested changes

2021-09-14 08:11 UTC, crypto-3dd commented on src/pages/assets/components/ReceiveDetail.tsx
> +    }
This would mean every time Ledger address would be only the `croxxx` type.

I think you can put a TODO over there, this section would be updated once @leejw51crypto brings support for Ledger on CRONOS

2021-09-16 14:16 UTC, crypto-3dd approved these changes

2021-09-16 14:17 UTC, merged