Problem: Validator APY and uptime additions
crypto-com/chain-desktop-wallet pull request #781
Opened 2021-11-01 11:52 UTC by cdc-Hitesh

![image](https://user-images.githubusercontent.com/68221858/139667387-1396387e-7c3e-4bc3-8832-ece17be50c5e.png)

2021-11-02 07:44 UTC, crypto-matto reviewed
1. The APY value is between 0 and 1, which we shall multiply the value 100 to get the APY in %
2. We may add sorting to `APY` and `Uptime` field

2021-11-02 09:22 UTC, crypto-matto requested changes
```

```
<img width="287" alt="Screenshot 2021-11-02 at 5 12 27 PM" src="https://user-images.githubusercontent.com/74586409/139818796-bddcfb32-3ca9-475b-9364-cb4158da3f2e.png">

2021-11-02 09:22 UTC, crypto-matto commented on src/pages/staking/staking.tsx
> +            apiClient.getValidatorUptimeByAddress(validator.validatorAddress),
```suggestion
            apiClient.getValidatorUptimeByAddress(validator.validatorAddress),
```

Definitely not a good idea to call API client hundred times here. 
Can we use a `getValidatorsUptime()` instead, which could return uptimes of an input array of validatorsAddressList?


<img width="287" alt="Screenshot 2021-11-02 at 5 12 27 PM" src="https://user-images.githubusercontent.com/74586409/139818796-bddcfb32-3ca9-475b-9364-cb4158da3f2e.png">

2021-11-02 09:22 UTC, crypto-matto commented on src/pages/staking/staking.tsx
> +
We shall call here
```
            apiClient.getValidatorsAverageApy([validator.validatorAddressList]),
            apiClient.getValidatorUptimeByAddress([validator.validatorAddressList]),
```

2021-11-02 09:25 UTC, crypto-matto commented
Is it possible to fetch the APY & uptime in one batch from `NodeRpcService.tsx` => `loadTopValidators()`?

2021-11-04 05:53 UTC, crypto-matto approved these changes

2021-11-05 07:38 UTC, XinyuCRO approved these changes

2021-11-09 06:32 UTC, crypto-eddy commented on src/pages/staking/staking.tsx
> +    // };
This can just be cleaned if not needed anymore

2021-11-10 06:54 UTC, cdc-Hitesh commented on src/pages/staking/staking.tsx
> +    // };
@crypto-matto  I think we can discard this PR right?

2021-11-10 09:13 UTC, crypto-matto commented on src/pages/staking/staking.tsx
> +    // };
Let me double check on this.

2021-11-11 08:14 UTC, crypto-matto commented
The validator list section is crashing after merged with latest dev branch. I'm investigating why. Don't merge it yet.

2021-11-11 18:59 UTC, crypto-matto commented
> The validator list section is crashing after merged with latest dev branch. I'm investigating why. Don't merge it yet.

Problem solved. It's due to the deprecated `WalletService.ts`

@cdc-Hitesh Is `WalletService.ts` gonna wipe out completely? We may create an extra PR to fix this.

2021-11-12 02:33 UTC, crypto-matto approved these changes

2021-11-12 09:35 UTC, XinyuCRO approved these changes

2021-11-12 15:47 UTC, crypto-eddy approved these changes

2021-11-12 15:47 UTC, crypto-eddy commented
> > The validator list section is crashing after merged with latest dev branch. I'm investigating why. Don't merge it yet.
> 
> Problem solved. It's due to the deprecated `WalletService.ts`. Another PR regarding to this issue #813 will be addressed separately.

Has this been fixed by now ?

2021-11-12 16:02 UTC, crypto-matto commented
> #813

Yes, this issue has been closed. 

> > > The validator list section is crashing after merged with latest dev branch. I'm investigating why. Don't merge it yet.
> > 
> > 
> > Problem solved. It's due to the deprecated `WalletService.ts`. Another PR regarding to this issue #813 will be addressed separately.
> 
> Has this been fixed by now ?

Yes. Issue #813 was closed. The `dev` branch is fine. This only happens on this `feature/#748/validatorList`, and the deprecated functions in `WalletService` are removed in commit [#34427cf](https://github.com/crypto-com/chain-desktop-wallet/pull/781/commits/34427cfc0817d06e6a3fd0798c1c2f36b51c7378)

2021-11-15 05:56 UTC, crypto-matto approved these changes

2021-11-15 05:56 UTC, merged