Feature (Fix #805): Allow users to specify manually destination address during bridge transactions
crypto-com/chain-desktop-wallet pull request #808
Opened 2021-11-11 04:53 UTC by crypto-matto

May have a better suggestion on the UI
<img width="691" alt="Screenshot 2021-11-11 at 12 52 46 PM" src="https://user-images.githubusercontent.com/74586409/141239466-c592ccdc-a67a-4735-a1d3-1c1571f6ae4a.png">

2021-11-11 06:30 UTC, crypto-eddy commented on src/pages/bridge/components/CronosBridgeForm.tsx
> +              I want to send funds to another destination address.
```suggestion
              I want to send funds to a custom destination address.
```

2021-11-11 06:35 UTC, crypto-eddy requested changes

2021-11-11 06:35 UTC, crypto-eddy commented on src/pages/bridge/components/CronosBridgeForm.tsx
>          setToAddress(tendermintAddress);
Looks like `destinationAddress` and `setToAddress` are being used for the same purpose.
Why not just use the address being set in `setToAddress`. It looks to me as a duplicate logic.

2021-11-11 07:22 UTC, crypto-matto commented on src/pages/bridge/components/CronosBridgeForm.tsx
>          setToAddress(tendermintAddress);
The `setToAddress` function is not updating `toAddress` immediately, and it doesn't have a callback, so we need an extra variable to update the formField value. 

Similar approach is often used in `Session` as well, where we first retrieve the latest session, store it in a variable, then update the session state
```
    const currentSession = await walletService.retrieveCurrentSession();
    const currentAsset = await walletService.retrieveDefaultWalletAsset(currentSession);

    setSession(currentSession);
```

Instead of update the session state right a way, then pass it to function.

```
    const currentSession = await walletService.retrieveCurrentSession();
    setSession(currentSession);
    const currentAsset = await walletService.retrieveDefaultWalletAsset(session);
```

2021-11-12 09:40 UTC, XinyuCRO approved these changes
LGTM

2021-11-12 09:40 UTC, XinyuCRO commented on src/components/RowAmountOption/RowAmountOption.tsx
> +  setSendingAmount?: (value: string) => void;
event callback props can start with `on`, eg `onSetSendingAmount` for better convention, but no big deal here

2021-11-12 10:29 UTC, crypto-eddy requested changes

2021-11-12 10:29 UTC, crypto-eddy commented on src/pages/bridge/components/CronosBridgeForm.tsx
>          setToAddress(tendermintAddress);
The difference is we are not mutating the session.

But here we have a `let destinationAddress` mutable variable being mutated several places. This type of coding is usually very prone to mistakes and bugs.

Also I'm seeing the same being repeated a couple of places. Try to see if there's a way to remove duplications.

2021-11-12 10:51 UTC, crypto-matto commented on src/components/RowAmountOption/RowAmountOption.tsx
> +  setSendingAmount?: (value: string) => void;
This is not a callback props. This is really used to update the `sendingAmount` state outside of its parent component. 
The event callback you're referring is `onAmountOption()` - an `onClick()` like function instead.
e.g. when `amount` option is clicked, do something. `setSendingAmount()` is also called due to this event callback.

2021-11-12 11:00 UTC, XinyuCRO commented on src/components/RowAmountOption/RowAmountOption.tsx
> +  setSendingAmount?: (value: string) => void;
what I mean callback is something in the child happened, notify outer, let the outer decide what to do,  in this context, it's just like `onClick`.  `setSendingAmount` sounds like an action, not an event name, no big deal here, just some naming convention

btw, child component shouldn't change parent component's state, it's an anti-pattern

2021-11-12 11:00 UTC, XinyuCRO approved these changes

2021-11-12 15:45 UTC, crypto-eddy approved these changes

2021-11-12 15:45 UTC, merged