[WIP][NFM] New Transaction History Model
crypto-com/chain-desktop-wallet pull request #809
Opened 2021-11-11 08:11 UTC by cdc-Hitesh

Hey @crypto-eddy @crypto-matto @XinyuCRO 

Please help me validate this approach.
What are your thoughts?

2021-11-11 08:22 UTC, XinyuCRO commented on src/service/rpc/ChainIndexingAPI.ts
> +  public async getMessagesByAccountAddress(userAddress: string, optionalMsgTypeName?: string) {
we can expose `page` & `pageSize` param to this function and let the UI layer (eg. table) choose which page to load, not to load all txs at one time. If the user has too many txs, it will take quite a long time to fetch, bad for performance and UX

2021-11-11 08:23 UTC, XinyuCRO commented on src/service/rpc/ChainIndexingAPI.ts
> +        queryURL
why request the same URL in this loop?

2021-11-11 08:28 UTC, XinyuCRO commented on src/service/rpc/ChainIndexingAPI.ts
> +  public async getMessagesByAccountAddress(userAddress: string, optionalMsgTypeName?: string) {
also we can make `optionalMsgTypeName` a type, the caller can get a hint when calling this function from the type list

```ts
type MesgTypeName = "MsgSend" | "Msgxxx"
```

2021-11-11 09:00 UTC, XinyuCRO commented on src/models/Transaction.ts
> +export interface CommonTransaction extends BaseCommonTransaction {
for the model definition, we can use a typescript technique union https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions 

```ts
export interface CommonAttributesByWallet {
  customParams?: { [key: string]: string }; // Note: We WILL dedicate a storage for `customParams` like totalBalance, totalRewards, estimatedApy etc.
  walletId: string;
  assetId?: string;
  assetType: UserAssetType;
}

export interface BaseCommonTransaction {
  walletId: string;
  assetId?: string;
  assetType: UserAssetType;
}

export interface StakingTransactionModel extends BaseCommonTransaction {
  walletId: string;
  assetId?: string;
  txType: "staking"
  data: StakingTransactionData;
}

export interface UnbondingDelegationModel extends BaseCommonTransaction {
  walletId: string;
  assetId?: string;
  txType: "unbonding"
  data: UnbondingDelegationData;
}

export type CommonTransaction =
  | StakingTransactionModel
  | UnbondingDelegationModel
```

for the persistence layer, it can only accept `CommonTransaction` type, don't care the inner structure,
for the caller, it will be safer & easier to know the inner type

```ts
  let tx: CommonTransaction = {...}

  if (tx.txType === 'staking') {
    // we can sure this is type safe
    tx.data.stakedAmount
  }

```

2021-11-11 09:46 UTC, cdc-Hitesh commented on src/service/rpc/ChainIndexingAPI.ts
> +  public async getMessagesByAccountAddress(userAddress: string, optionalMsgTypeName?: string) {
> also we can make optionalMsgTypeName a type, 

Yes, I agree with you. That's why I have pulled all the supported message types in `staticConfig`. Making it a type that make it fail safe.


>we can expose page & pageSize param to this function and let the UI layer (eg. table) choose which page to load, not to load all txs at one time.

This is a good thought on performance! Not sure if this is a good time to introduce this feature . May be separate ticket for this?  cc @crypto-matto  What's your say?

2021-11-11 09:46 UTC, cdc-Hitesh commented on src/service/rpc/ChainIndexingAPI.ts
> +        queryURL
Yes, correct.
 It's a work in progress function. 
I should have marked it as `TODO`. Thanks for noticing

2021-11-11 09:46 UTC, cdc-Hitesh commented on src/models/Transaction.ts
> +export interface CommonTransaction extends BaseCommonTransaction {
Hmm. 
That is an interesting approach.
Just wondering if keeping a single model with a dedicated type for `txType` behaves well.

Like `txType: "staking" | "transfer"`

2021-11-12 04:16 UTC, crypto-matto commented on src/service/rpc/ChainIndexingAPI.ts
> +  public async getMessagesByAccountAddress(userAddress: string, optionalMsgTypeName?: string) {
For our current setup, all the transaction data are all stored in local storage through the below process:
`syncAll()` => `syncTransactionsData()` => `fetchAndUpdateTransactions()` => `fetchAndSaveTransfers()` => `fetchAllTransferTransactions()` => `saveTransfers()`
Therefore, the issue @XinyuCRO was referring might not exactly be the case as we don't need to call the api every time we change pages on the UI. We're just getting these data from local storage.

However, syncing time could be quite lengthy when users first open their app, as we're loading all data in one batch & update our local storage. I do agree with @XinyuCRO suggestion on exposing `page` & `pageSize` in the ChainIndexingAPI for future use, just that we may still need a certain set of parameter input (may be `page: 1` & `pageSize: 0`? ) to return us all transactions for the moment. 

In a separate PR in the future, we may revise the way we insert data in local storage, rather than everytime we retrieve all transactions data & reinsert the whole thing, we may try to fetch only latest transactions. That I believe could drastically reduce our current app loading time.

2021-11-28 16:32 UTC, cdc-Hitesh commented
cc @XinyuCRO @crypto-matto @crypto-eddy 
Please review the logic design for the new model.
I will have to do some extra finishing for this, as this is becoming a large piece of code.
Would request your thoughts, will continue once I come back from the vacation.
Thanks

2021-11-28 17:05 UTC, cdc-Hitesh commented
cc @XinyuCRO @crypto-matto @crypto-eddy 
Please review the logic design for the new model.

2021-12-03 07:21 UTC, crypto-matto requested changes

2021-12-03 07:21 UTC, crypto-matto commented on src/storage/StorageService.ts
> +      totalBalance: rewardCustomParams.customParams.totalBalance,
The app is crashing as `rewardCustomParams.customParams` is `null`. 
All customParams using `this.db.commonAttributeStore.findOne()` could potentially causing this issue. 

Should add `|| '0'` at the back of each assignment as well. 
e.g. 
``` totalBalance: rewardCustomParams.customParams.totalBalance || '0' ```

2021-12-03 07:23 UTC, crypto-matto commented on src/models/Transaction.ts
> +export interface CommonTransaction extends BaseCommonTransaction {
I'm seeing you using the TypeScript Unions 👍🏻.

2021-12-03 07:27 UTC, crypto-matto commented on src/storage/StorageService.ts
> +    let stakingTxRecord = await this.db.commonTransactionStore.find<StakingTransactionRecord>({
I find there are lots of `...tx` variables using `let` yet isn't gonna change in values. Use `const` instead.

2021-12-03 07:34 UTC, crypto-matto commented on src/models/Transaction.ts
> +    totalBalance?: string
May be we should include `unbondingBalance` as well?

2021-12-03 07:35 UTC, crypto-eddy commented on src/config/GeneralConfig.ts
> +  // isTxHistoryMigrated: boolean;
Can be cleaned up if not needed

2021-12-03 07:40 UTC, crypto-matto commented on src/storage/StorageService.ts
> +      await this.db.commonTransactionStore.update<CommonTransactionRecord>({
Is it possible to update in one single `update` command with an array, instead of calling multiple times in a forEach loop? 
Reference: https://docs.mongodb.com/manual/reference/method/db.collection.update/#modify-a-field-using-the-values-of-the-other-fields-in-the-document

2021-12-07 07:10 UTC, cdc-Hitesh commented on src/storage/StorageService.ts
> +      totalBalance: rewardCustomParams.customParams.totalBalance,
Yes correct noted.

2021-12-07 07:11 UTC, cdc-Hitesh commented on src/storage/StorageService.ts
> +    let stakingTxRecord = await this.db.commonTransactionStore.find<StakingTransactionRecord>({
I agree!
I wanted `eslint` to take care of this for me 😆 (it's easy to see all such errors in a log) . But thanks for the notice.

2021-12-07 07:15 UTC, cdc-Hitesh commented on src/models/Transaction.ts
> +    totalBalance?: string
I haven't seen any model using `unbondingBalance`, as I have referenced to current models. 
If you suggest we can keep that as well?

@crypto-matto

2021-12-07 07:16 UTC, cdc-Hitesh commented on src/config/GeneralConfig.ts
> +  // isTxHistoryMigrated: boolean;
Yes noted.
I have kept it to indicate a possible approach for data migration from old style to this latest style.

I will surely get rid of such comments.

2021-12-07 07:18 UTC, cdc-Hitesh commented on src/storage/StorageService.ts
> +      await this.db.commonTransactionStore.update<CommonTransactionRecord>({
You are absolutely correct on this.
But the design of data updating is such that we need to call one by one.

If it `inserted` transactions, we can do batch calls.
For update I will have to figure out, will check your article.

2021-12-08 09:17 UTC, cdc-Hitesh commented on src/storage/StorageService.ts
> +      totalBalance: rewardCustomParams.customParams.totalBalance,
Resolved.

2021-12-08 11:31 UTC, XinyuCRO commented on src/storage/StorageService.ts
> +      console.log(`[insertCommonTransactionRecords] Upserting record, txHash : ${record.txHash} | TxType: ${record.txType}`)
this line causes too much `console.log` when user has too many TXs

2021-12-08 11:31 UTC, XinyuCRO commented on src/storage/StorageService.ts
> +      totalBalance: (rewardCustomParams && rewardCustomParams.customParams) ? rewardCustomParams.customParams.totalBalance : '0',
use lodash `_.get`

2021-12-08 14:03 UTC, mannutech commented on src/storage/StorageService.ts
> +      totalBalance: (rewardCustomParams && rewardCustomParams.customParams) ? rewardCustomParams.customParams.totalBalance : '0',
Is using a third party library worth here? 
I mean in terms of size cost.

2021-12-08 14:03 UTC, mannutech commented on src/storage/StorageService.ts
> +      console.log(`[insertCommonTransactionRecords] Upserting record, txHash : ${record.txHash} | TxType: ${record.txType}`)
I can suppress that.

2021-12-08 14:07 UTC, XinyuCRO commented on src/storage/StorageService.ts
> +      totalBalance: (rewardCustomParams && rewardCustomParams.customParams) ? rewardCustomParams.customParams.totalBalance : '0',
oh, just use `xx?.xx` is fine, this line is too redundant

2021-12-08 14:14 UTC, cdc-Hitesh commented on src/storage/StorageService.ts
> +      totalBalance: (rewardCustomParams && rewardCustomParams.customParams) ? rewardCustomParams.customParams.totalBalance : '0',
I agree. 
Let's change it to use `xx?.xx` format

2021-12-08 14:29 UTC, cdc-Hitesh commented on src/storage/StorageService.ts
> +      totalBalance: (rewardCustomParams && rewardCustomParams.customParams) ? rewardCustomParams.customParams.totalBalance : '0',
Pushed

2021-12-09 06:22 UTC, XinyuCRO approved these changes

2021-12-10 04:28 UTC, crypto-matto commented
I think it's better to merge this after the CRC20 support is released, and we could earn more time in testing the support of this with CRC20 tokens as well.

2021-12-24 04:06 UTC, crypto-matto commented
Encountering this when all my staking balances are 0 & clicked `Delegation Management` in `Staking` Page
<img width="1259" alt="螢幕截圖 2021-12-24 上午10 22 30" src="https://user-images.githubusercontent.com/74586409/147314916-29d22665-d64d-4e53-ae3a-59adc09f30b9.png">

2021-12-24 12:53 UTC, cdc-Hitesh commented
> ## Existing issues
> * [ ]  Encountering this when all my staking balances are 0 & clicked `Delegation Management` in `Staking` Page
> 
> <img alt="螢幕截圖 2021-12-24 上午10 22 30" width="1259" src="https://user-images.githubusercontent.com/74586409/147314916-29d22665-d64d-4e53-ae3a-59adc09f30b9.png">
> 
> * [x]  Transaction records are not sorted by DateTime in desc order
> 
> <img alt="螢幕截圖 2021-12-24 下午12 08 56" width="945" src="https://user-images.githubusercontent.com/74586409/147315155-83209d8e-cca3-488d-9384-e773b58d5baf.png">
> 
> * [ ]  Wallet balances on Home page now takes extremely longer to load, when I'm switching to other pages and then come back
> 
> <img alt="螢幕截圖 2021-12-24 下午12 49 11" width="1265" src="https://user-images.githubusercontent.com/74586409/147318326-898875b4-220c-4264-a517-02627bbaa86d.png">
> 
> * [ ]  Transaction records are not consistent. Sometimes it is loading more, sometimes it is less. I guess there's so
> 
> <img alt="螢幕截圖 2021-12-24 下午1 04 08" width="937" src="https://user-images.githubusercontent.com/74586409/147318745-b26cc15c-2433-4eba-ac95-2172981bcdc4.png">
> 
> <img alt="螢幕截圖 2021-12-24 下午1 01 32" width="933" src="https://user-images.githubusercontent.com/74586409/147318740-3cf7c336-80bb-48e8-bfa2-dd116106a358.png">
> 
> * [ ]  If switching between different assets, and then an asset is first loading its transaction record, the transaction records will stay as the previous assets' records until it finishes loading. I believe we may add a load spinning icon or this
> 
> <img alt="螢幕截圖 2021-12-24 下午1 04 24" width="936" src="https://user-images.githubusercontent.com/74586409/147318748-45efcf97-2706-4a17-b8ab-16ef0b39c92b.png">

That's wonderful testing points @crypto-matto  .
Can I request the account private key to test them at my end?

2022-01-07 03:59 UTC, crypto-matto commented
## Breaking changes
- Ditch the loading of transaction histories for all assets in 1 single function call, since we now support much more assets. Replace `fetchAndSaveTransfers()` with `fetchAndSaveTransfersByAsset()`. The transaction histories are only loaded when users are inside a specific asset detail page. 
- Transaction histories will not be saved inside local storage

2022-01-07 07:02 UTC, crypto-matto commented
Hey @cdc-Hitesh, I have a few questions:

Since I'd like to include the MsgType in Assets Page -> Transaction Table field
1. Is it the function `getMessagesByAccountAddress()` could technically replace the original `fetchAllTransferTransactions()` API call? 
2. Am I able to input an array of string with multiple `optionalMsgTypeName` instead in `getMessagesByAccountAddress(userAddress: string, optionalMsgTypeName?: string)`
3. Could you also revise `Transaction.ts => type TransactionData` into:
```
export interface TransactionData {
  hash: string;
  memo: string | null;
  date: string;
  status: TransactionStatus;
  assetSymbol: string;
  msgTypeName?: string;
}
```
As such, inside `fetchAndSaveTransfersByAsset() => const transferTransactions` , we may use a more general `const transactions` instead, which includes multiple `msgTypeName`?

2022-01-07 07:26 UTC, cdc-Hitesh commented
> 1. Is it the function `getMessagesByAccountAddress()` could technically replace the original `fetchAllTransferTransactions()` API call?
> 2. Am I able to input an array of string with multiple `optionalMsgTypeName` instead in `getMessagesByAccountAddress(userAddress: string, optionalMsgTypeName?: string)`
> 3. Could you also revise `Transaction.ts => type TransactionData` into:

As replied on Slack,
1. Yes we can do that
2. Yes, the indexing api supports sending multiple msg types
3. Okay, we can include msgTypeName? in the interface.

2022-01-12 06:20 UTC, crypto-matto commented
Updated Layout on Assets => Transaction
<img width="961" alt="Screenshot 2022-01-12 at 2 19 04 PM" src="https://user-images.githubusercontent.com/74586409/149074567-99d09121-9622-4c96-855f-12b1f4012ae3.png">

2022-01-12 17:19 UTC, crypto-matto approved these changes

2022-01-12 17:23 UTC, cdc-Hitesh commented on src/service/TransactionHistoryService.ts
> +              txType: "transfer",
I think we can extract out this labels `"transfer"` to a constant variable?
What do you say?

2022-01-13 04:09 UTC, XinyuCRO submitted a review, later dismissed

2022-01-13 04:34 UTC, crypto-matto submitted a review, later dismissed

2022-01-13 05:25 UTC, crypto-matto approved these changes

2022-01-13 05:26 UTC, merged