CRC20 backend - Signing Token Transfer transactions
crypto-com/chain-desktop-wallet pull request #849
Opened 2021-12-01 10:16 UTC by crypto-eddy

2021-12-08 04:09 UTC, crypto-matto commented
I'm seeing `mainnetSymbol` is always `CRO` for whatever assets. Is it intended?

2021-12-08 07:56 UTC, crypto-eddy commented
> I'm seeing `mainnetSymbol` is always `CRO` for whatever assets. Is it intended? Since we used `mainnetSymbol` in a lot of places on `price` & `value` field, so that we could also display a proper pricing for testnet TCRO.

The mainnet symbol should be the token symbol, I've fixed that issue, should be okay in the next commit.

2021-12-09 03:23 UTC, crypto-matto requested changes

2021-12-09 03:23 UTC, crypto-matto commented on src/service/TransactionHistoryService.ts
> +          default:
Missing case for CRC_20_TOKEN
```
case UserAssetType.CRC_20_TOKEN:
```
This would result in CRC_20_TOKEN assets falling into:
```
throw TypeError('Not supported yet');
```

2021-12-09 03:23 UTC, crypto-matto commented on src/service/TransactionHistoryService.ts
> +  public async fechTokensAndPersistBalances(session: Session | null = null) {
Typo `fetchTokensAndPersistBalances`

2021-12-09 03:23 UTC, crypto-matto commented on src/service/TransactionHistoryService.ts
> +    await this.fechTokensAndPersistBalances(session);
When there's an asset fall into the `default case` in `fetchTokensAndPersistBalances()` and throwing an error
```
        switch (asset.assetType) {
          case UserAssetType.TENDERMINT:
            break;
          case UserAssetType.EVM:
            await this.fetchCurrentWalletCRC20Tokens(asset);
            break;
          default:
            throw TypeError('Not supported yet');
        }
```
This line will stuck in the `await` and anything after that will not run at all.

2021-12-09 16:28 UTC, cdc-Hitesh commented on src/service/TransactionHistoryService.ts
> +                  status: TransactionStatus.SUCCESS,
Are we not checking the `status` value here?

2021-12-09 16:31 UTC, cdc-Hitesh commented on src/service/TransactionSenderService.ts
> +            accountSequence: 0,
shall we set `accountNumber` and `accountSequence` to something invalid as default like `-1`

2021-12-09 16:33 UTC, cdc-Hitesh commented on src/service/TransactionSenderService.ts
> +            value: web3.utils.toWei(transferRequest.amount, 'ether'),
`transferRequest.amount` , can it be `undefined` or `null`

2021-12-09 16:34 UTC, cdc-Hitesh commented on src/service/TransactionSenderService.ts
> +          const staticTokenTransferGasLimit = 130_000;
Can we pull this constant somewhere on the top?

2021-12-09 16:36 UTC, cdc-Hitesh commented on src/service/signers/EvmTransactionSigner.ts
> +    const chainId = transaction?.asset?.config?.chainId || 338;
Can we pull `338` as a constant on top?

2021-12-09 16:37 UTC, cdc-Hitesh commented on src/service/signers/EvmTransactionSigner.ts
> +      value: 0,
Some token transfers can have optional non-zero ethereum value as well. 
We may need to input `value` as well.

2021-12-09 16:38 UTC, cdc-Hitesh commented on src/service/signers/EvmTransactionSigner.ts
> +    const web3 = new Web3('');
Is there a benefit to instantiating Web3 in every function?
We can expose a single instance.

2021-12-09 16:41 UTC, cdc-Hitesh reviewed
Left a few comments

2021-12-10 01:09 UTC, crypto-eddy commented on src/service/TransactionHistoryService.ts
> +          default:
This place is where we are loading tokens for each asset/coin type, CRC_20_TOKEN is already a token type, it's not needed here. Only main coins tokens are loaded over here.

2021-12-10 01:10 UTC, crypto-eddy commented on src/service/TransactionHistoryService.ts
> +    await this.fechTokensAndPersistBalances(session);
Good catch

2021-12-10 01:13 UTC, crypto-eddy commented on src/service/TransactionSenderService.ts
> +            value: web3.utils.toWei(transferRequest.amount, 'ether'),
For tokens transfer, recipient is usually null, and the actual transfer happens in the encoded tokens transfer data. I will update.

2021-12-10 01:16 UTC, crypto-eddy commented on src/service/signers/EvmTransactionSigner.ts
> +    const web3 = new Web3('');
This is just for the utility function access, not much use, it will get garbage collected when the function execution steps out of that method scope.

2021-12-10 01:18 UTC, crypto-eddy commented
I've now responded to all the review comments and I've pushed the necessary updates.

2021-12-10 01:53 UTC, crypto-matto approved these changes

2021-12-10 02:06 UTC, crypto-matto commented
I'm seeing that if one of my CRC20 token balance got cleared out (Let's say I all traded them all on VVS Swap), while my balances all the corresponding tokens are updated, my supposed-to-be cleared out token's balance is not updated & still there. May have to investigate why.

2021-12-10 14:34 UTC, crypto-matto commented
> I'm seeing that if one of my CRC20 token balance got cleared out, while my balances all the corresponding tokens are updated, my supposed-to-be cleared out token's balance is not updated & still there.
> 
> Let's say my balance is having 10 USDT, and I spent all buying VVS on VVS Swap
> 
> * VVS balance is updated correctly
> * CRO balance after paying gas fee is updated correctly
> * USDT balance stays at 10 USDT
> 
> May have to investigate why.

I’m safely say that even after 8 hours the supposed-to-be zero balance asset is not updated, while all my non-zero balances assets are all updated.

I guess it’s about the backend is not removing the zero balance asset from existing DB record.

2021-12-11 17:19 UTC, crypto-matto commented
### Issues to be solved
- [ ] Zero balances assets is not removing & stays when the old balance
- [ ] Settings -> Node Configurations hide all non-CRO assets settings

2021-12-15 07:46 UTC, crypto-matto approved these changes
LGTM

2021-12-15 07:47 UTC, merged